#  ╭━━━┳╮╱╱╱╱╱╭━━━╮╱╱╱╱╱╱╱╱╭╮
#  ┃╭━╮┃┃╱╱╱╱╱╰╮╭╮┃╱╱╱╱╱╱╱╭╯╰╮
#  ┃╰━━┫┃╭┳╮╱╭╮┃┃┃┣━━┳━╮╭━┻╮╭╋━━╮
#  ╰━━╮┃╰╯┫┃╱┃┃┃┃┃┃╭╮┃╭╮┫╭╮┃┃┃┃━┫
#  ┃╰━╯┃╭╮┫╰━╯┣╯╰╯┃╰╯┃┃┃┃╭╮┃╰┫┃━┫
#  ╰━━━┻╯╰┻━╮╭┻━━━┻━━┻╯╰┻╯╰┻━┻━━╯
#  ╱╱╱╱╱╱╱╭━╯┃
#  ╱╱╱╱╱╱╱╰━━╯

settings: # Основные настройки
  # Префикс всех сообщений
  messagesPrefix: "&fSkyPayments &e> &f"
  # Название файла с настройками сообщений
  langFile: "ru_RU.yml"

cart: # Настройки корзины
  command: # Параметры команды для открытия корзины
    # Если false - команда не будет зарегистрирована
    enable: true
    # Название команды
    name: "cart"
    # Альтернативы этой команде
    aliases:
      - "корзина"

shop: # Данные Вашего магазина
  shopID: 1
  serverID: 2
  secretKey: '19O_9!bBZI1Aa9nRD6KgkNuk'

database: # Настройки базы данных
  # Доступные типы: MYSQL, SQLITE
  type: SQLITE
  # Префикс для таблиц
  tablePrefix: "skydonate_"
  mysql:
    # Хост
    host: "localhost"
    # Порт
    port: 3306
    # Название базы данных
    databaseName: "test"
    # Пользователь
    user: "root"
    # Пароль
    password: "-"
    # Дополнительные параметры подключения. Изменяйте, если знаете, для чего это нужно
    arguments: "?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false"