name: SkyPayments
main: ru.skydonate.skypayments.SkyPayments
version: "1.2"
api-version: "1.13"
author: _GameDoctor_
description: "Plugin to automatically issue goods on your Minecraft server. Developed by SkyDonate team."
website: skydonate.ru

commands:
  skypayments:
    permission: "skypayments.admin"
    description: Main SkyPayments command
    aliases:
      - sdonate
      - skydonate
      - spayments
    usage: /<command>